# Generated by Django 5.2.6 on 2025-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProbioticBacteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('strain', models.CharField(max_length=100)),
                ('plant_host', models.TextField()),
                ('function', models.TextField()),
                ('mode_of_action', models.TextField()),
                ('reference', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Probiotic Bacteria',
            },
        ),
    ]
